#include "drishti/core/config.h"

#if DRISHTI_HAVE_MLIR

#include "mlir/IR/MLIRContext.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/TypeID.h"

namespace mlir::LLVM {
class LLVMDialect;
class LLVMFunctionType;
class LLVMTargetExtType;
class LLVMX86AMXType;
class LLVMPPCFP128Type;
class LLVMFuncOp;
class CallOp;
class BrOp;
class CondBrOp;
class SwitchOp;
class ConstantOp;
class GlobalOp;
class BitcastOp;
class IndirectBrOp;
class InvokeOp;
class GEPOp;
class LoadOp;
class StoreOp;
class ZExtOp;
class ComdatOp;
class ComdatSelectorOp;
class AliasOp;
class IFuncOp;
class GlobalCtorsOp;
class GlobalDtorsOp;
}  // namespace mlir::LLVM

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMDialect)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMDialect)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMFunctionType)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMFunctionType)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMTargetExtType)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMTargetExtType)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMX86AMXType)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMX86AMXType)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMPPCFP128Type)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMPPCFP128Type)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMFuncOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LLVMFuncOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::CallOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::CallOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::BrOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::BrOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::CondBrOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::CondBrOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::SwitchOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::SwitchOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::ConstantOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::ConstantOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::GlobalOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::GlobalOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::BitcastOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::BitcastOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::IndirectBrOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::IndirectBrOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::InvokeOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::InvokeOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::GEPOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::GEPOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::LoadOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::LoadOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::StoreOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::StoreOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::ZExtOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::ZExtOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::ComdatOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::ComdatOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::ComdatSelectorOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::ComdatSelectorOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::AliasOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::AliasOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::IFuncOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::IFuncOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::GlobalCtorsOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::GlobalCtorsOp)

MLIR_DECLARE_EXPLICIT_TYPE_ID(mlir::LLVM::GlobalDtorsOp)
MLIR_DEFINE_EXPLICIT_TYPE_ID(mlir::LLVM::GlobalDtorsOp)

#endif  // DRISHTI_HAVE_MLIR
